### ISSUE TITLE
train 

### ISSUE THREAD

**Issue by yy835055664** [msh9184/April2022_trainer#1]
Hi, thank you very much for your project. While reproducing your code, there is a problem, ZeroDivisionError: division by zero. Please how to solve this problem.

Traceback (most recent call last):
  File "/home/yxk/anaconda3/envs/tdnn/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/yxk/yy/April2022_trainer-main/trainSpeakerNet.py", line 176, in main_worker
    loss, traineer, lr = trainer.train_network(train_loader, it, verbose=(args.gpu == 0))
  File "/home/yxk/yy/April2022_trainer-main/SpeakerNet.py", line 103, in train_network
    return (loss/cnt, top1/cnt, lr)
ZeroDivisionError: division by zero

**Comment by msh9184** [comment]
Hi, I guess your train_list format is wrong.

After creating the train list file and putting it in the `./list` directory, could you try the command line? (e.g., `CUDA_VISIBLE_DEVICES=0,1,2 python trainSpeakerNet.py --train_list ./list/train_vox1-vox2.txt`)

The train list file format should be made like `[data_path data_label]`, for example,
```
/home/shmun/DB/VoxCeleb/VoxCeleb2/dev/wav/id00012/21Uxsk56VDQ/00001.wav id00012
/home/shmun/DB/VoxCeleb/VoxCeleb2/dev/wav/id00012/21Uxsk56VDQ/00002.wav id00012
```

You can refer to the following example file `train_vox1-vox2.txt`:
https://drive.google.com/file/d/1T63XkJfKWyAJ3slgBTLXZg9g_w2ccqbm/view?usp=sharing

**Comment by yy835055664** [comment]
> Hi, I guess your train_list format is wrong.
> 
> After creating the train list file and putting it in the `./list` directory, could you try the command line? (e.g., `CUDA_VISIBLE_DEVICES=0,1,2 python trainSpeakerNet.py --train_list ./list/train_vox1-vox2.txt`)
> 
> The train list file format should be made like `[data_path data_label]`, for example,
> 
> ```
> /home/shmun/DB/VoxCeleb/VoxCeleb2/dev/wav/id00012/21Uxsk56VDQ/00001.wav id00012
> /home/shmun/DB/VoxCeleb/VoxCeleb2/dev/wav/id00012/21Uxsk56VDQ/00002.wav id00012
> ```
> 
> You can refer to the following example file `train_vox1-vox2.txt`: https://drive.google.com/file/d/1T63XkJfKWyAJ3slgBTLXZg9g_w2ccqbm/view?usp=sharing

**Comment by yy835055664** [comment]
Thank you very much, indeed as you said, the training set label problem.
